# Generated by Django 4.2.6 on 2023-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_fixedamount_nonfixedamount_delete_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonfixedamount',
            name='uploadfile',
            field=models.FileField(default='default_value_for_uploadfile', upload_to='uploads/'),
        ),
    ]
