# Generated by Django 4.2.6 on 2023-10-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_nonfixedamount_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonfixedamount',
            name='uploadfile',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
