# Generated by Django 4.2.6 on 2023-10-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_nonfixedamount_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonfixedamount',
            old_name='uploadfile',
            new_name='upload_file',
        ),
    ]
